import { Pet } from "@/types/pet";

export const seedPets: Pet[] = [
  {
    status: "perdido",
    id: "seed-1",
    name: "Toby",
    photos: [
      "/images/pet-dog.jpg",
      "/images/guide-1.jpg",
      "/images/guide-2.jpg",
      "/images/guide-3.jpg",
    ],
    description:
      "Labrador color marrón, muy amigable. Lleva collar rojo y chapita con nombre. Se perdió cerca de la plaza el domingo a la tarde. Responde al nombre y se lleva muy bien con chicos.",
    animalType: "perro",
    date: "2026-04-05",
    location: "Av. Corrientes 1234, CABA",
    contactPhone: "+54 11 5555-1234",
    contactEmail: "familia.toby@example.com",
    createdAt: "2026-04-05T10:00:00Z",
    sex: "macho",
    breed: "Labrador",
    ageMonths: 44,
    color: "Marrón",
    weightKg: 28,
    heightCm: 60,
    hasCollar: true,
    hasTag: true,
    microchipped: true,
    neutered: true,
    vaccinated: true,
    friendlyWithKids: true,
    trained: true,
  },
  {
    id: "seed-2",
    status: "perdido",
    name: "Luna",
    photos: [
      "/images/pet-cat.jpg",
      "/images/guide-4.jpg",
      "/images/guide-5.jpg",
      "/images/guide-6.jpg",
    ],
    description:
      "Gata siamesa de ojos celestes. Responde al nombre de Luna y es muy sociable. Se escapó por una ventana del patio interno. Muy cariñosa con personas y otros gatos.",
    animalType: "gato",
    date: "2026-04-08",
    location: "Parque Centenario, CABA",
    contactPhone: "+54 11 5555-5678",
    contactEmail: "hola.luna@example.com",
    createdAt: "2026-04-08T15:30:00Z",
    sex: "hembra",
    breed: "Siamesa",
    ageMonths: 30,
    color: "Crema y marrón",
    weightKg: 4,
    heightCm: 25,
    hasCollar: false,
    hasTag: false,
    microchipped: true,
    neutered: true,
    vaccinated: true,
    friendlyWithKids: true,
    trained: false,
  },
  {
    id: "seed-3",
    status: "perdido",
    name: "Bella",
    photos: ["/images/guide-1.jpg", "/images/pet-dog.jpg"],
    description:
      "Perrita caniche blanca, muy pequeña. Se escapó por el portón cuando abrieron para sacar la basura. Tiene un moño rosa en la cabeza.",
    animalType: "perro",
    date: "2026-04-10",
    location: "Villa Urquiza, CABA",
    contactPhone: "+54 11 5555-2468",
    contactEmail: "bella.familia@example.com",
    createdAt: "2026-04-10T09:15:00Z",
    sex: "hembra",
    breed: "Caniche",
    ageMonths: 18,
    color: "Blanco",
    weightKg: 5,
    heightCm: 28,
    hasCollar: true,
    hasTag: true,
    microchipped: false,
    neutered: true,
    vaccinated: true,
    friendlyWithKids: true,
    trained: true,
  },
  {
    id: "seed-4",
    status: "en adopción",
    name: "Simba",
    photos: ["/images/guide-4.jpg", "/images/pet-cat.jpg"],
    description:
      "Gato atigrado naranja, muy grande y peludo. Se perdió cerca del parque. Es tímido con extraños pero se acerca si le mostrás comida.",
    animalType: "gato",
    date: "2026-04-11",
    location: "Palermo, CABA",
    contactPhone: "+54 11 5555-1357",
    contactEmail: "simba.casa@example.com",
    createdAt: "2026-04-11T17:45:00Z",
    sex: "macho",
    breed: "Mestizo",
    ageMonths: 48,
    color: "Naranja atigrado",
    weightKg: 6,
    heightCm: 30,
    hasCollar: false,
    hasTag: false,
    microchipped: false,
    neutered: true,
    vaccinated: true,
    friendlyWithKids: false,
    trained: false,
  },
  {
    id: "seed-5",
    status: "encontrado",
    name: "Rocco",
    photos: ["/images/guide-2.jpg", "/images/pet-dog.jpg"],
    description:
      "Bulldog francés negro. Ronca fuerte y es muy cariñoso. Se escapó durante un paseo cuando un auto lo asustó.",
    animalType: "perro",
    date: "2026-04-12",
    location: "Belgrano, CABA",
    contactPhone: "+54 11 5555-9876",
    contactEmail: "rocco.hogar@example.com",
    createdAt: "2026-04-12T12:00:00Z",
    sex: "macho",
    breed: "Bulldog francés",
    ageMonths: 24,
    color: "Negro",
    weightKg: 12,
    heightCm: 32,
    hasCollar: true,
    hasTag: true,
    microchipped: true,
    neutered: false,
    vaccinated: true,
    friendlyWithKids: true,
    trained: true,
  },
  {
    id: "seed-6",
    status: "perdido",
    name: "Mía",
    photos: ["/images/guide-5.jpg", "/images/pet-cat.jpg"],
    description:
      "Gata negra de ojos verdes. Se escapó del balcón del 3er piso. Muy ágil y asustadiza, responde a su nombre.",
    animalType: "gato",
    date: "2026-04-13",
    location: "Caballito, CABA",
    contactPhone: "+54 11 5555-8765",
    contactEmail: "mia.negra@example.com",
    createdAt: "2026-04-13T08:30:00Z",
    sex: "hembra",
    breed: "Mestiza",
    ageMonths: 36,
    color: "Negro",
    weightKg: 3.5,
    heightCm: 22,
    hasCollar: true,
    hasTag: false,
    microchipped: true,
    neutered: true,
    vaccinated: true,
    friendlyWithKids: true,
    trained: false,
  },
];
